name: ECS Release

on:
  workflow_dispatch:
  release: 
    types: created

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 552464281736.dkr.ecr.us-east-1.amazonaws.com
  ECS_SERVICE: csiprojectservice
  ECS_CLUSTER: csiprojecttest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Docker build
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 552464281736.dkr.ecr.us-east-1.amazonaws.com
        docker build -t teamprojectf .
        docker tag teamprojectf:latest 552464281736.dkr.ecr.us-east-1.amazonaws.com/teamprojectf:latest
        docker push 552464281736.dkr.ecr.us-east-1.amazonaws.com/teamprojectf:latest
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
